### PR TITLE
Fixes the documentation for mpileup --output-BP-5.

### LINKED ISSUE #1534: mpileup: --output-BP-5 switches output column 7 and 8
when using the --output-BP-5 option, the position and read id columns are switched
```
samtools mpileup --output-QNAME --output-BP in.bam
test_chr	25	A	1	^!,	I	1	id_1

```
```
samtools mpileup --output-QNAME --output-BP-5 in.bam
test_chr	25	A	1	^!,	I	id_1	24
```

### PR DESCRIPTION
**Pull request by jkbonfield**
The original intention of this was to modify the orientation of the `--output-BP` field, as originally requested.  Due to lack of research into the original code, sadly this was moved to the end of the list of columns.  We didn't test in conjunction with everything else turned on.

It was decided that we should not fix this as it would become incompatible with the previous release, so it's now been documented.

However given it's now its own column instead of modifying the existing column, `--output-BP-5` is no longer mutually exclusive with `--output-BP`.

Fixes #1534 (albeit not in the ideal way)

### CODE REVIEW

**Comment by jmarshall** [comment]
Both documentation paragraphs need a “(Column only present when *…option…* is used.)” sentence, and looking at the code suggests that in 1.14 the `--output-BP-5` column actually appears **before** the “Additional read tag field columns”. (So in between the two halves of `--output-extra` — brillant! :smile:)

(#1281 is an example of where `samtools-1.10 mpileup` column ordering was altered in 1.11 to agree with its documentation — except in that case there was the advantage that it was also being altered to agree with the ≤1.9 behaviour.)

**Comment by jkbonfield** [comment]
Hmm, I'll check again to make sure I've got the documentation right then.

My personal preference, given it's recent and somewhat obscure, would be to fix as intended, but I think we're fearful of the mess that could ensue with it being in different positions.  I have sympathy for that if I believe it was in common usage, but I expect it really isn't!

**Comment by jkbonfield** [comment]
Updated the ordering again.

The code is pretty cryptic and it's not immediately obvious that the bit-field also represents a partial ordering too.  (I say partial as some fields still appear out of order.)

File: bam_plcmd.c [hunk 1]
```diff
@@ -1106,7 +1106,6 @@ int bam_mpileup(int argc, char *argv[])
             break;
         case  14:
             mplp.flag |=  MPLP_PRINT_QPOS5;
-            mplp.flag &= ~MPLP_PRINT_QPOS;
```
Comment (daviesrob) [inline bam_plcmd.c:1109]: You also need to remove the test on `MPLP_PRINT_QPOS5` on line [1104](https://github.com/samtools/samtools/blob/e56146ca/bam_plcmd.c#L1104)
