### PR TITLE
Remove use of C variables starting in _ from bam_consensus.c.

### LINKED ISSUE #2248: Makefile bam_consensus.o Error
Please help me ~~~~

Samtools (v.1.22/v.1.22.1) installation failed.

An error occurred while compiling the 'bam_consensus.o' file during the make process.

The error appears as follows:
> 
> "bam_consensus.c:1403:20: error: expected identifier or ‘(’ before numeric constant"
> 
>  1403 |             double _P = q2p[qual];
> 
> make: *** [Makefile:140: bam_consensus.o] Error 1
>

### PR DESCRIPTION
**Pull request by jkbonfield**
This conflicts with _P definition in newlib's ctype.h in cygwin.

Fixes #2248

### CODE REVIEW

File: bam_consensus.c [hunk 1]
```diff
@@ -1335,14 +1335,13 @@ int calculate_consensus_gap5(hts_pos_t pos, int flags, int depth,
 
 #ifdef K2
         int hb = 0;
-#define _ 0
-        static int X[16] = {_,0,1,_,2,_,_,_,3,_,_,_,_,_,_,_};
+        const int x = 0;
+        static int X[16] = {x,0,1,x,2,x,x,x,3,x,x,x,x,x,x,x};
         int i, base1 = X[p->base4];
         for (i = p->seq_offset-K2; i <= p->seq_offset+K2; i++) {
             int base = i >= 0 && i < p->b.core.l_qseq ? X[bam_seqi(seq,i)] : _;
```
Comment (jmarshall) [inline bam_consensus.c:1342]: Missed one here, and similarly above. Would be nice if this could use `seq_nt16_int` instead of `X`, but those 4s might be a bit of a pain…

**Comment by jkbonfield** [comment]
I also added another tiny commit which isn't technically related to the original issue, but I don't feel like creating multiple PRs and then someone having to deal with resolving any conflicts plus having to do all the testing and evaluation twice.

For local users, my assessment was on this file:

```
samtools coolensus -r LG08:1-1000000 ~jkb/scratch/data/Female_pacbio.bam -o /dev/nul
```

The md5sum consensus didn't differ, but the `-f pileup` output did due to subtle quality value changes, due to avoiding repeated rounding conversions.
